server:
  port: 8098
spring:
  application:
    name: "ms_test_chat_whatsapp"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/chat_app_db"
